---
# Notes:
# This task will configure a devices Management interface details, ie, IP, Subnet Mask, Gateway, DNS
# You could use it to update deviecs DNS settings or set devices back to DHCP or to Static IP
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Change Management Config
      cisco.meraki.devices_management_interface:
        state: present
        serial: Q3AJ-####-####
        wan1:
          usingStaticIp: true
          staticIp: 192.168.20.181
          staticSubnetMask: 255.255.255.0
          staticGatewayIp: 192.168.20.1
          staticDns:
          - 192.168.20.2
          - 8.8.8.8


