---
# Notes:
# Conceptually this play is designed to copy a Template network where VPN NAT Translation is already configured
# Then change the subnets, then enable VPN, and now VPN is enabled change the VPN NAT Translation subnet
# As of 2/2/24 there are no APIs to configure VPN NAT Translation settings, logically configure it in a template for scaleable deployment
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Clone Network
      cisco.meraki.networks:
        state: present
        organizationId: #######
        name: Clone
        notes: Cloned_with_anisble
        copyFromNetworkId: L_#################
        productTypes:           
          - appliance
          - wireless
        timeZone: Australia/Sydney
      register: create_network
      # This Task will clone a network from the source detailed in copyFromNetworkId value
      # Secondly is important to register the output as we need the new Network ID for later tasks

    - name: Change VLAN Subnets to make it unqiue
      cisco.meraki.networks_appliance_vlans:
        state: present
        id: '10'
        vlanId: 10
        applianceIp: 10.10.40.1
        cidr: 10.10.40.0/24
        name: Management
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: 10.10.40.0/24
      # This task will change the current Subnet to make it unquie so we can enable a unquie subnet in the SDWAN
      # You should do this task for every subnet you are going to enable

    - name: Enable Cloned Network as a Spoke
      cisco.meraki.networks_appliance_vpn_site_to_site_vpn:
        state: present
        hubs:
        - hubId: L_#################
        mode: spoke
        networkId: "{{ create_network.meraki_response.id }}"
      # This task will enable the MX as a spoke 
      # The hubId value is just the Network ID of the network with the hub in it, (L_### or N_###)

    - name: Update VPN NAT Translation Subnet
      cisco.meraki.networks_appliance_vlans:
        state: present
        id: '10'
        vlanId: 10
        applianceIp: 10.10.40.1
        cidr: 10.10.40.0/24
        name: Management
        networkId: "{{ create_network.meraki_response.id }}"
        subnet: 10.10.40.0/24
        vpnNatSubnet: 192.168.40.0/24 
      # This task will now go back and useing the vpnNatSubnet will set the subnet used for VPN NAT Translation