---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Network
      cisco.meraki.networks:
        state: present
        organizationId: #######
        name: Clone
        notes: Cloned_with_anisble
        copyFromNetworkId: L_##################
        productTypes:           
          - appliance
          - wireless
        timeZone: Australia/Sydney
      register: create_network
      # This Task will clone a network from the source detailed in copyFromNetworkId value
      # Register the output if you need the new Network ID for later tasks, you can then call it later with the next line
      # networkId: "{{ create_network.meraki_response.id }}"
