---
# Notes: This playbook will enable a hub first then enable a spoke, you could do a loop and list many networks from a file in the spoke task
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Enable the Hub
      cisco.meraki.networks_appliance_vpn_site_to_site_vpn:
        state: present
        mode: hub
        networkId: L_################## #Update with the Network to make a Hub

    - name: Enable the Spoke
      cisco.meraki.networks_appliance_vpn_site_to_site_vpn:
        state: present
        hubs:
        - hubId: L_################HUB## #Update with the Network ID of the Hub
        mode: spoke
        networkId: L_##############SPOKE## #Update with the Network to make a Spoke
      # The hubId value is just the Network ID of the network with the hub in it (it can be L_### or N_###)