---
# Notes:
# This play will get the DDNS names for the Active URL, you can change the result filtering to also show WAN1 and WAN2 IPs
# This would be useful if you need to get the IPs or a DNS name for each WAN to input into another platform
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get MX Info
      cisco.meraki.devices_management_interface_info:
        serial: Q3##-####-####
      register: result

    - name: Show MX DDNS
      ansible.builtin.debug:
        msg: "{{ result | json_query('meraki_response.ddnsHostnames.activeDdnsHostname') }}"
