---
# Notes: This playbook will set 2 SYSLOG servers for a network by the Network ID in the task
- hosts: localhost
  tasks:
    - name: Set SYSLOG Server
      cisco.meraki.networks_syslog_servers:
        networkId: L_#########
        servers:
        - host: 192.168.20.25
          port: 514
          roles: #These have to be present for the target network, i.e. if there are no switches in the network it will error if you use role "switch event log"
          - Flows
          - URLs
          - Wireless event log
        - host: 20.33.44.2
          port: 443
          roles: 
          - Flows
          - Wireless event log